version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - npm install aws-cli
      - npm install @aws-sdk/client-lambda
  pre_build:
    commands:
      # S3からリダイレクトの設定ファイルを取得(なければからのjsonオブジェクトを持つファイルを作成)
      - |
        if aws s3 ls s3://$REDIRECT_CONFIG_BUCKET/$REDIRECT_CONFIG_FILE; then
          aws s3 cp s3://$REDIRECT_CONFIG_BUCKET/$REDIRECT_CONFIG_FILE function/$REDIRECT_CONFIG_FILE
        else
          echo "{}" > function/$REDIRECT_CONFIG_FILE
        fi
      - cd function
      # ファイルのパッケージ化
      - zip -r ../function.zip index.mjs $REDIRECT_CONFIG_FILE
      - cd ../
      # Lambdaを更新してArnを取得
      - FUNCTION_ARN=$(aws lambda update-function-code --function-name $FUNCTION_NAME --region us-east-1 --zip-file fileb://function.zip --publish --query 'FunctionArn' --output text)
      - export FUNCTION_ARN
      # CloudFrontの設定を取得
      - DISTRIBUTION_CONFIG=$(aws cloudfront get-distribution-config --id $CLOUD_FRONT_ID --query 'DistributionConfig' --output json)
      # 新しくCloudFrontの設定を作成(Lambda@Edgeの紐付けを変更)
      - UPDATED_CONFIG=$(echo $DISTRIBUTION_CONFIG | jq '.DefaultCacheBehavior.LambdaFunctionAssociations.Items[0].LambdaFunctionARN = "'$FUNCTION_ARN'"')
      - UPDATED_CONFIG=$(echo $UPDATED_CONFIG | jq '.DefaultCacheBehavior.LambdaFunctionAssociations.Items[0].EventType = "viewer-request"')
      - UPDATED_CONFIG=$(echo $UPDATED_CONFIG | jq '.DefaultCacheBehavior.LambdaFunctionAssociations.Quantity = 1')
      # CloudFrontのEtagを取得
      - ETAG=$(aws cloudfront get-distribution-config --id $CLOUD_FRONT_ID --query 'ETag' --output text)
      # LambdaのステータスがActiveになるまで待機
      - node function/check-lambda-status.js
  build:
    commands:
      # CloudFrontの設定を更新
      - aws cloudfront update-distribution --id $CLOUD_FRONT_ID --distribution-config "$UPDATED_CONFIG" --if-match $ETAG
